### ISSUE TITLE
Inconvenient to work with BottomSearchBar

### ISSUE THREAD

**Issue by Grishy** [WrathChaos/react-native-bottom-search-bar#4]
Hello,

It would be cool to be able to change the text box from `BottomSearchBar`
Now, for every change in the field, I write its value in the state of the App component.
Like this:
```js
this.state = {
    text: "",
    list: [
        "Finish my changes",
        "Push my commits to GitHub",
        "Open a pull request",
    ]
};

...

<BottomSearchBar
    homeButtonIconComponent={<Text>😀</Text>}
    iconComponent={<Text>🖋</Text>}
    buttonOnPress={() => {
        this.setState({
            text: "",
            list: [...this.state.list, this.state.text],
        })
    }}
    onChangeText={(e) => {
        this.setState({
            text: e,
        })
    }}
    disableButtonIcon={true}
    searchBoxText={this.state.text}
    buttonText="Add"
/>
```

There is also no way to edit the text box. It would be convenient to have access to the value of `<TextInput>`
This would solve many problems.

Thanks for a good example,
Grishy

**Comment by WrathChaos** [comment]
@Grishy I transferred this issue to the related library :)

**Comment by Grishy** [comment]
Oh, I did not see that these are different projects. thanks

**Comment by WrathChaos** [comment]
For the BouncyCheckbox onPress issue. You can simply use `onPress={() => {}}` It has handle your onPress function after the animation, but I have callback the check value on the onPress, if you need it?

**Comment by WrathChaos** [comment]
@Grishy We can continue BouncyCheckbox's issue on https://github.com/WrathChaos/react-native-bouncy-checkbox/issues/6

**Comment by WrathChaos** [comment]
About the` BottomSearchBar`'s issue. Let me test it first :) I will inform you.

**Comment by WrathChaos** [comment]
@Grishy I've made it more customizable :) Now, you can use all TextInput's API. 

Please check this out:
# [Release 0.1.3 🤩🥳](https://github.com/WrathChaos/react-native-bottom-search-bar/releases/tag/0.1.3)
